version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: sokothai_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - symfony

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - 25:25
      - "8002:80"
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    depends_on:
      - db
    environment:
      PMA_ARBRITARY: 1
      PMA_HOST: db
    networks:
      - symfony

  php:
    build: php72
    ports:
    - "8072:80"
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - symfony
    working_dir: /var/www/sokothai

networks:
  symfony:

volumes:
  mariadb-data: